### ISSUE TITLE
find-library doesn't "work"

### ISSUE THREAD

**Issue by bjourne** [slavapestov/factor#1185]
find-library only runs when the vocab is compiled. So the missing gtk_init problem happened because `gtk.ffi` was compiled on @mrjbq7's machine, he has `/usr/lib/libgtk-x11-2.0.so.0` so that was the path that was hardcoded into the binary. 

It's not so easy to get around that problem short of going back to dlopening development so:s. You would need to have `find-library` run from a startup hook or something and then have the path it finds injected in the binary code. 

I think `start_object_updater` in image.cpp loads all the dlls it can find in the image when Factor loads. You'd have to fix that code to call out to ``/sbin/ldconfig -p`` to find the right path to your so file. It could work but would be very messy.

**Comment by mrjbq7** [comment]
@erg should we close this?

**Comment by erg** [comment]
Sure! Works with deploy.

**Comment by erg** [comment]
Closing, if anyone has problems leave a comment.
