### ISSUE TITLE
images tuples become opaque when loading images.viewer.prettyprint

### ISSUE THREAD

**Issue by jonenst** [slavapestov/factor#1225]
Pretty printing image objects as images is nice (```USE: images.viewer.prettyprint```), but it should be possible to revert back to the string tuple representation. Maybe through a per-image right-click ->"show as tuple" ? Also add a way to globally revert for all images more convenient than ```[ M\ image pprint* forget ] with-compilation-unit``` ?

**Comment by mrjbq7** [comment]
Fixed in c329631e259d19a9fa1ffd180dffb4a0e9635d06, for now default to not prettyprinting images this way (except XKCD, because @erg and its awesome).
