### ISSUE TITLE
gc crash when reading from files

### ISSUE THREAD

**Issue by bjourne** [slavapestov/factor#1289]
Here is a minimal example of the crash Doug found when stress-testing with afl:

```factor
USING: accessors arrays byte-arrays formatting io io.buffers
io.encodings.binary io.files io.private kernel memory
namespaces sequences sequences.private ;
IN: test3
QUALIFIED: unix.ffi

: some-alloc ( y -- w )
    drop 80 f <array> ;

: my-read-ifd ( -- ifd )
    7 read 2 read 4 read 4 read
    19 f <array>
    2nip 2nip ;

: my-read-ifds ( tiff -- )
    input-stream get
    [ buffer>> 0 >>fill 0 >>pos drop ]
    [ handle>> fd>> 256 unix.ffi:SEEK_SET unix.ffi:lseek drop ] bi
    2 read drop
    13 [
        my-read-ifd
    ] replicate
    some-alloc drop
    555 f <array>
    over [ length ] [ set-nth ] bi
    my-read-ifds ;

"/etc/passwd" binary <file-reader>
[
    V{ } clone my-read-ifds
] with-input-stream
```
The code runs an infinite loop which allocates more and more memory so it should end when Factor can't grow the heap further. Instead it crashes:

    assertion "(parent->current_gc && parent->current_gc->op == collect_growing_heap_op) || parent->data->seg->in_segment_p((cell)obj)" failed: file "../vm/collector.hpp", line 28

**Comment by bjourne** [comment]
I think it's in `M\ input-port stream-read-unsafe`. Say you have a block #1, you increase the stack height by 1 so now `D 0` is uninitialized. Then that block has block #2 and #3 as successors. In #2 `D 0` is set but not in #3. Then both #2 and #3 are followed by #4 in which you do a gc. The problem is that now in #4 you do not know whether `D 0` is an initialized location or not.

**Comment by bjourne** [comment]
Don't think there is any way to solve the problem in the general case. What slots are initialized in the stack depends on what way through the cfg execution took before it reached the gc. Only way I can think of is to fix the compiler so it doesn't introduce gaps into the stacks in the first place.

**Comment by erg** [comment]
Is this only a problem with running out of memory, or is the problem everywhere?

**Comment by bjourne** [comment]
Everywhere. It's a delicate problem because if you trace to few roots that's bad and if you trace to many that's bad too. You must only trace exactly those that are live and no else. It doesn't crash so often though because it can only crash when an allocation fills up the nursery and there is two different paths to that allocation and there is one or more scrub slots in the gc map. So if you change some of the numbers in the example, say 555 to 444, the nursery will not fill up in the right location and the bug won't be triggered.

**Comment by bjourne** [comment]
Smaller crash:

```factor
USING: arrays byte-arrays kernel memory sequences ;
IN: test5

TUPLE: tup2 a b c d ;

: (my-generator) ( k -- n )
    20 f <array> 20 f <array> assert=
    ! Allocates a byte array so large that the next allocation will
    ! trigger a gc.
    drop 2097103 <byte-array> ;

: run-test ( -- lag )
    9 iota [ (my-generator) ] map
    ! The gc map for this allocation has a scrub slot
    0 9 1 tup2 boa ;

run-test drop
```

**Comment by erg** [comment]
How is this bug doing after the recent patches?

**Comment by bjourne** [comment]
It should be gone hopefully!

**Comment by erg** [comment]
Sweet. Nice work! Closing.
