### ISSUE TITLE
gtk-samples.hello-world does not work

### ISSUE THREAD

**Issue by hyphz** [slavapestov/factor#1293]
Running the sample file gtk-samples.hello-world under Windows does not work. With either version of the "all-in-one" package installed (gtk2 or gtk3), it produces an error saying that signal_connect_data cannot be found in libobject-2-0-0.dll. This may be a misspelled DLL name as the library that comes with GTK is called libgobject-2-0-0.dll (the name factor uses omits the g). However copying libgobject to libobject gives a memory protection error.

**Comment by hyphz** [comment]
Yup, it's a typo in basis\gobject\ffi\ffi.factor in the Windows OS case.

**Comment by mrjbq7** [comment]
Fixed in 7c30ae8ab6bcc681b52297177ecd993112723f18, thanks!!
