### ISSUE TITLE
Bug in EBNF?

### ISSUE THREAD

**Issue by mrjbq7** [slavapestov/factor#1303]
```factor
! Bug, ebnf?
EBNF: parse-foo
foo  = "+"|" " => [[ first ]]
;EBNF
```

This happens:

```
"+" parse-foo => "+"
" " parse-foo => 32
"X" parse-foo => error
```

I would have thought the first one would be 43 (``CHAR: +``)

**Comment by erg** [comment]
It's not a bug, this is the intended behavior.

```factor
! Bug, ebnf?
EBNF: parse-foo
foo  = "+" => [[ first ]] |" " => [[ first ]]
;EBNF
```

**Comment by mrjbq7** [comment]
Ah, you have to wrap it.

```factor
! Bug, ebnf?
EBNF: parse-foo
foo  = ("+"|" ") => [[ first ]]
;EBNF
```

**Comment by mrjbq7** [comment]
Okay, I'm getting close to solving the EBNF bug for ``tokenize``.

Seems like a rule being parsed twice, the first time it does what I expect, the second time it doesn't.
