### ISSUE TITLE
Move reject to core sequences?

### ISSUE THREAD

**Issue by mrjbq7** [slavapestov/factor#1305]
In sequences.extras, we have ``reject``, ``reject-as``, and ``reject!``, that are basically just versions of:

 ``[ ... not ] filter``

We have almost 120 "not filters" in core/basis/extra.

Perhaps these would be cleaner if we made reject an official thing.

Is reject a good name? It's the name Ruby uses in [Array::reject](http://ruby-doc.org/core-2.2.0/Array.html#method-i-reject).

**Comment by bjourne** [comment]
I like it. In Scheme and Clojure it's called `remove` and in (e)lisp `remove-if`. But the `remove` word is already taken.

**Comment by erg** [comment]
:+1:

**Comment by mrjbq7** [comment]
@erg do you like the name?  Or we could call it ``remove-when`` or ``remove-if`` or ...

**Comment by erg** [comment]
-when and -if sound like names of branching combinators. I think reject
makes more sense than remove.

On Tue, May 12, 2015 at 4:58 PM, John Benediktsson <notifications@github.com

**Comment by mrjbq7** [comment]
Okay, added ``reject`` (and figured I'd add ``assoc-reject``, while I was doing it).
