### ISSUE TITLE
Missing word when attempting USE: http.server.static

### ISSUE THREAD

**Issue by bpollack** [slavapestov/factor#1311]
On attempting to `USE: http.server.static`, I get

```
resource:basis/http/server/static/static.factor

3: USING: calendar kernel math math.order math.parser namespaces
8: html.templates.fhtml http http.server http.server.responses
                                        ^
resource:basis/http/server/cgi/cgi-docs.factor

5: { $values { "responder" file-responder } }
                                         ^
No word named “file-responder” found in current vocabulary search path
```

which prevents the file from loading. Patch coming imminently, but wanted to make sure I didn't forget this.

**Comment by mrjbq7** [comment]
Did you ``USE: http.server`` first?

**Comment by bpollack** [comment]
No, I did not, and I just realized that's what's going on. Is this a bug or a...feature?

**Comment by mrjbq7** [comment]
I noticed it before, there's some bootstrapping issue with the sub-vocabs requiring ``http.server``, and they are loaded by ``http.server``:

https://github.com/slavapestov/factor/blob/master/basis/http/server/server.factor#L318

**Comment by mrjbq7** [comment]
Workaround is to ``USE: http.server`` first, but if you find a nicer way, it would be good to fix it at some point.

**Comment by bjourne** [comment]
I think the cycle is in `basis/http/server/cgi/cgi-docs.factor`. I found it by randomly commenting out the code in vocabs.

**Comment by bjourne** [comment]
I made a ghetto fix for the cycle. Something more robust would be to defer loading all `-docs.factor` files to after the main vocabs have been loaded. Then I think almost all cyclic dependency problems would go away.

**Comment by mrjbq7** [comment]
Breaks, because DEFER: actually defines a ``<static>`` and then...

```
==== file-server:

resource:extra/file-server/file-server.factor

30:     [
33:         <static>
                    ^
More than one vocabulary defines a word named “<static>”


==== websites.concatenative:

resource:extra/websites/concatenative/concatenative.factor

95: : <gitweb> ( path -- responder )
97:         swap <static> enable-cgi >>default
                         ^
More than one vocabulary defines a word named “<static>”
```

**Comment by mrjbq7** [comment]
Maybe a different fix here: 36c002f567d3b489caa7b5c733e5ddaf089326bf

**Comment by mrjbq7** [comment]
Actually, a better fix is to ``DEFER:`` in http.server.static.

29f94f8a653f1dbdebead8dd4b0c1b65285fd6b7

**Comment by bjourne** [comment]
Oh, right I missed that. That's a much better fix!
