### ISSUE TITLE
Wrong behaviour of :> - Cannot execute a word before it has been compiled

### ISSUE THREAD

**Issue by nedzadarek** [slavapestov/factor#1312]
```factor
USE: locals
: qux ( -- x ) 42 ;
: foo ( -- x ) qux ;
qux ! 42
foo ! 42

: bar ( -- x ) 
[let 10 :> qux qux ] ;
bar ! 10
qux ! Error: Cannot execute a word before it has been compiled
foo ! 42 - works
```
Acording to documentation of `:>`, `qux` should work.

**Comment by bjourne** [comment]
Is that because you name your local variable qux and there is already a word with that name?

**Comment by nedzadarek** [comment]
Yes.

**Comment by mrjbq7** [comment]
Normally shadowed words require disambiguation (e.g., ``FROM: assocs => change-at ;``).

Thats not a very nice error message we generate, and probably no "fix" besides renaming unless we make it restartable, or always allow shadowing.

**Comment by bjourne** [comment]
Is there a use case for shadowing like nedzadareks example?

**Comment by mrjbq7** [comment]
I've run into this when I have some "common-sounding" words in a vocab and mix with locals, but only occasionally.

**Comment by mrjbq7** [comment]
@bjourne fixed this, closing.
