### ISSUE TITLE
load failure for compiler.cfg.gvn on mac32

### ISSUE THREAD

**Issue by erg** [slavapestov/factor#1329]
```
Load failures

compiler.cfg.gvn
compiler.cfg.gvn.testing
Details:
==== compiler.cfg.gvn:

No suitable arithmetic method
left    f
right   0
generic -


==== compiler.cfg.gvn.testing:

resource:extra/compiler/cfg/gvn/testing/testing.factor

3: USING: accessors assocs compiler.cfg compiler.cfg.debugger
4: compiler.cfg.graphviz compiler.cfg.gvn
                                         ^
No suitable arithmetic method
left    f
right   0
generic -
```

**Comment by mrjbq7** [comment]
I don't see this on mac64.

**Comment by erg** [comment]
It doesn't even happen all the time on mac32.

**Comment by bjourne** [comment]
Hasn't most of what was in `extra/compiler/cfg/gvn` been migrated/merged to `compiler/cfg/value-numbering/`? So maybe the test is triggering a failure in some old unused code that should be cleaned up?

**Comment by mrjbq7** [comment]
The opposite, I think. The ``compiler.cfg.gvn`` is the new global value numbering that should replace the old one but is not enabled in master right now.

**Comment by ajvondrak** [comment]
> is not enabled in master right now

Probably because it was being all [lame](https://github.com/slavapestov/factor/issues/671#issuecomment-8670229). Also, not pointing any fingers here or anything, but that @ajvondrak guy *did* kinda stop working on it... :sweat_smile:

**Comment by erg** [comment]
Random failure that stopped happening, possibly fixed with the VM work.

Completely unrelated to gvn compiler pass and its author working or not working. :smiley_cat: :smile_cat: 

Closing for now.
