### ISSUE TITLE
Better out-of-the-box emacs editor integration

### ISSUE THREAD

**Issue by mrjbq7** [slavapestov/factor#1330]
How about this?

```diff
diff --git a/basis/editors/emacs/emacs.factor b/basis/editors/emacs/emacs.factor
index 683ddca..f65ecf0 100644
--- a/basis/editors/emacs/emacs.factor
+++ b/basis/editors/emacs/emacs.factor
@@ -1,5 +1,5 @@
 USING: combinators.short-circuit editors kernel make
-math.parser namespaces sequences system vocabs ;
+math.parser namespaces sequences system tools.which vocabs ;
 IN: editors.emacs
 
 SINGLETON: emacsclient
@@ -9,7 +9,8 @@ SYMBOL: emacsclient-path
 
 HOOK: default-emacsclient os ( -- path )
 
-M: object default-emacsclient ( -- path ) "emacsclient" ;
+M: object default-emacsclient ( -- path )
+    "emacsclient" [ which ] [ or ] bi ;
 
 M: emacsclient editor-command ( file line -- command )
     [
@@ -23,4 +24,3 @@ M: emacsclient editor-command ( file line -- command )
     ] { } make ;
 
 os windows? [ "editors.emacs.windows" require ] when
```

On my Mac, that sets it to ``/usr/bin/emacsclient``.

Getting it to work with Emacs.app is still a manual process.

**Comment by mrjbq7** [comment]
P.S. @bjourne I don't use emacs so maybe you can opine on this :-)

**Comment by mrjbq7** [comment]
Come to think of it, we could do this on most of the editors, where it looks for a ``foo-path`` defined and then just defaults to ``"foo"`` if not found.

@erg thoughts?

**Comment by bjourne** [comment]
Seems right to me. The other emacs error is that the command line to emacsclient should have `--alternate-editor emacs` so that emacs is started if the daemon isn't running.

**Comment by mrjbq7** [comment]
Hmm, I tried ``--alternate-editor emacs`` and it doesn't seem to work from inside Factor's UI.  It does, however, work from the command-line but "takes over" the process until emacs is exited.

So for right now, I'm not going to change that -- but you're welcome to send a pull request if you'd like!

**Comment by mrjbq7** [comment]
Fixed using ``?find-in-path`` instead of ``tools.which`` in 071704072cba094c7527052580a1073a5a87247d.
