### ISSUE TITLE
safe_fclose retries on EINTR

### ISSUE THREAD

**Issue by erg** [slavapestov/factor#1335]
``fclose`` and ``close`` are not supposed to retry on ``EINTR``.

See #908.

**Comment by mrjbq7** [comment]
Does it?

```c++
void factor_vm::safe_fclose(FILE* stream) {
  for (;;) {
    if (fclose(stream) == EOF)
      io_error();
    else
      break;
  }
}
```

Doesn't it just ``io_error()`` or break?

**Comment by erg** [comment]
``io_error`` retries on ``EINTR`` doesn't it?

On Wed, Jun 3, 2015 at 11:32 AM, John Benediktsson <notifications@github.com

**Comment by mrjbq7** [comment]
Oh, yep you're right.  It only sets ``general_error`` when not ``EINTR``.

**Comment by mrjbq7** [comment]
Hah, should call it ``io_error_if_not_EINTR()``.

**Comment by erg** [comment]
+1
