### ISSUE TITLE
Funky "has not been compiled" problem

### ISSUE THREAD

**Issue by mrjbq7** [slavapestov/factor#1338]
Start a fresh Factor instance, and paste this into the UI listener.

```factor
:: sieve ( n -- primes )
    n 1 + t <array> :> sieve
    f 0 sieve set-nth
    f 1 sieve set-nth

    2 n [a,b] [| i |
        i sieve nth [
            2 i * n i <range> [| j |
                f j sieve set-nth
            ] each
        ] when
    ] each

    sieve [ drop ] selector [ each-index ] dip ;
```

You will get two restarts: one for ``locals``, one for ``math.ranges``.

After choosing the "right" vocabs to use, try running ``100 sieve``.

You get this error:

```
Cannot execute a word before it has been compiled
word sieve
```

**Comment by mrjbq7** [comment]
Maybe related to #1340.

**Comment by mrjbq7** [comment]
Maybe something to do with a local named the same as a word.

This one is a little weird too, breaks initially with wrong stack effect.

```
:: foo ( n -- seq )
    n <bit-array> :> foo
    foo ;
```

**Comment by mrjbq7** [comment]
This is still a bug, has to do with shadowing somehow a local with the same name as the word.

**Comment by mrjbq7** [comment]
Related are deferred locals because of similar leakage out of the scope of the word definition.

Paste this into a new listener:

```factor
:: foo ( n -- seq )
    0 :> a
    n <bit-array> :> foo
    foo
```

When you get the restart for ``<bit-array>``, just hit escape to cancel the window.

Now paste this:

```factor
:: bar ( x -- y ) x a + ;
```

You get this:

```
You have found a bug in locals. Please report.
args [ ]
obj  a
```

**Comment by mrjbq7** [comment]
@bjourne if you want another locals project, this "leakage" would be a good one :-)

**Comment by bjourne** [comment]
It's easy to explain but maybe not so easy to solve. First this and esc on the restart:
```factor
:: foo ( n -- seq ) 0 :> a n <bit-array> :> foo foo
```
Then you can write `a` or `n` and Factor finds the words, but it should instead throw "No word named..." errors. If you run `manifest get qualified-vocabs>> last words>>` you see that the variables have "escaped" and become part of the global namespace.

**Comment by mrjbq7** [comment]
Maybe we could add a new ``<extra-words>`` to ``qualified-vocabs`` and modify it and then pop it off after we exit the word definition?

I dunno, just a thought.

**Comment by bjourne** [comment]
I think that's what the locals code is doing. The problem is that when the restartable error is thrown, the code exits prematurely so no `<extra-words>` is popped. I tried

```over use-words [ call( -- quot ) ] [ swap unuse-words ] [ ] cleanup```

It plugs the leaks, but then the restarts doesn't work at all.

**Comment by mrjbq7** [comment]
Maybe at the end of the locals definitions we can cleanup / remove any that were added during the parsing of the word?

**Comment by bjourne** [comment]
No because we can't guarantee that the end is ever reached. But I added `manifest get clone [ clone ] change-qualified-vocabs manifest set` before `use-words` and it maybe works. Then changes only happen to the manifest bound in the continuation.

**Comment by mrjbq7** [comment]
@bjourne fixed this, closing.
