### ISSUE TITLE
Locals off-by-one restart?

### ISSUE THREAD

**Issue by mrjbq7** [slavapestov/factor#1340]
Somehow the restart for ``<bit-array>`` causes ``seq`` not to be found as a local.

```factor
:: foo ( n -- seq )
    n <bit-array> :> seq
    seq ;
```

**Comment by bjourne** [comment]
Looks like any restart before `:>` can trigger it. Eg `:: foo ( -- m ) 2 >base64 :> v v ;`  Could it be something with the restart that doesn't completely restore the previous context?
