### ISSUE TITLE
fixnum shift not becoming fixnum-shift-fast

### ISSUE THREAD

**Issue by mrjbq7** [slavapestov/factor#1342]
This should optimize the ``shift`` to ``fixnum-shift-fast`` but it doesn't:

```factor
[
    { fixnum object } declare
    integer>fixnum dup 0 >= [
        neg shift even? not
    ] [ 2drop f ] if
] optimized.
```

It clearly knows that the inputs and outputs of ``shift`` are fixnum, but I'm not sure why it doesn't optimize to ``fixnum-shift-fast``.

```factor
[
    integer>fixnum dup 0 fixnum>= [
        -1 fixnum*fast fixnum-shift 1 >R R> fixnum-bitand 0 eq?
        [ f ] [ \ t ] if
    ] [ 2drop f ] if
]
```

**Comment by ajvondrak** [comment]
Should it? The only thing we know about the top of the stack here is that it is:
* a fixnum (class propagation from the `declare` + `integer>fixnum`)
* non-positive (value range propagation into the branch from `dup 0 >=` then `neg`)

We can (and the compiler already does) optimize `shift` to `fixnum-shift`. But `fixnum-shift-fast` is for [small shifts](https://github.com/slavapestov/factor/blob/master/basis/compiler/tree/cleanup/cleanup.factor#L86-L92) (where we can't possibly overflow to a bignum), which this is not:

```factor
[
    { fixnum object } declare
    integer>fixnum dup 0 >= [
        neg shift even? not
    ] [ 2drop f ] if
] build-tree optimize-tree
[ #if? ] find nip children>> first
[ { [ #call? ] [ word>> \ fixnum-shift eq? ] } 1&& ] find nip
node-input-infos [ interval>> ] map .

! V{
!     T{ interval
!         { from { -576460752303423488 t } }
!         { to { 576460752303423487 t } }
!     }
!     T{ interval
!         { from { -576460752303423487 t } }
!         { to { 0 t } }
!     }
! }

cell-bits tag-bits get - [ neg ] keep [a,b]

! T{ interval { from { -60 t } } { to { 60 t } } }
```

**Comment by bjourne** [comment]
But aren't you forgetting that the second shift operand is <= 0 so the result will always be a fixnum if the  first operand is a fixnum? E.g `<fixnum> 1234 shift` could overflow `<fixnum> -123456789 shift` can't.

**Comment by bjourne** [comment]
I misunderstood. The problem isn't overflow it's that the shift operand must fit into an 8-bit register to be able to use the `shr` and `shl` instructions. Maybe it would still be possible to optimize an expression like `{ fixnum } declare -2000 shift` better (result will always be 0) but maybe it's not worth the bother.

**Comment by mrjbq7** [comment]
Okay, I'm closing this for now then.
