### ISSUE TITLE
Can you kill threads?

### ISSUE THREAD

**Issue by bjourne** [slavapestov/factor#1387]
Someone asked about it on irc and it seems like the answer is no. You can list the running threads with `threads.` But you can't make Factor shot down a running thread. Seems like you should be able to.

**Comment by erg** [comment]
You can't kill threads. The closest I got was annotating every word with a flag that says whether it should keep running or not and putting a yield somewhere. Then you could run a thread in the UI and stop it on demand. It's a hack and terrible for performance, but it helped someone find an infinite loop once on irc.

We should concentrate on a new parser, better support for locals/fry/walker and their semantics, a correct compiler/gc, and then a plan for multithreading that allows killing threads.

**Comment by jonenst** [comment]
And there's CTRL+C t which throws an exception for busy infinite loops in
the listener
Le 16 juil. 2015 11:42 PM, "Doug Coleman" <notifications@github.com> a
écrit :

**Comment by erg** [comment]
There's nothing to do here right now, and if we get native threads someday then we won't need to be reminded of being able to kill them. Closing!

**Comment by mrjbq7** [comment]
Why not keep feature issues open?

**Comment by mrjbq7** [comment]
Also, shouldn't we be able to implement ``kill-thread`` and ``wait-for-thread`` on our cooperative threads?

**Comment by erg** [comment]
In general we can, but this one in particular is not something we can do without native threading, and literally the second thing you would implement is the ability to kill threads.

``wait-for-thread`` is in another issue #1407.
