### ISSUE TITLE
Missing version info on Windows builds?

### ISSUE THREAD

**Issue by mrjbq7** [slavapestov/factor#1404]
The Windows builds have ``Factor version-missing x86.32 (1685, git-label-missing...``

Need to put the right version numbers there.

**Comment by erg** [comment]
Where is this?

On startup I get:
``
Press F1 at any time for help.
Factor 0.98 x86.64 (1681, heads/master-0-gb9c0255, Wed Dec 24 10:35:50 2014)
[Microsoft Visual C++ 190022816] on windows
```

**Comment by mrjbq7** [comment]
Latest nightly build x86-32.

**Comment by erg** [comment]
But where is the message appearing? On startup?

**Comment by mrjbq7** [comment]
Yeah on startup via the ``system:version-info`` word.

**Comment by mrjbq7** [comment]
@erg the windows x86-32 builder has this in its error just now:

```
Factor version-missing x86.32 (1682, git-label-missing, Tue Jul 28 19:48:28 2015)
[Microsoft Visual C++ 190022816] on windows
```

Any idea why version-info isn't working?

**Comment by erg** [comment]
The ``Nmakefile`` just uses env vars. ``factor.cmd`` sets them up, so we should call ``factor.cmd`` (the one in the build directory via ``absolute-path`` because windows launches the program relative to the cwd of the parent).

Fixed.
