### ISSUE TITLE
json parser segfaults

### ISSUE THREAD

**Issue by erg** [slavapestov/factor#1412]
```factor
"https://hacker-news.firebaseio.com/v0/" http-get nip json>
```

**Comment by mrjbq7** [comment]
Removing the ``declare`` and ``-unsafe`` words, gets me this from ``stream-json-read``:

```
Sequence is immutable
element  f
index    0
sequence f
```

**Comment by mrjbq7** [comment]
Considering that that URL gives you HTML instead of JSON, this is an error when parsing a non-JSON document with a JSON reader?

**Comment by erg** [comment]
Who cares what you give it? ``json>>`` should never sefault.

**Comment by mrjbq7** [comment]
Yeah obviously, I wasn't saying segfaults are okay, I was narrowing in on what caused the crash.

Fixed in 663fba1d7d4cf3242343fe5327ee5147d73a76a3.

**Comment by erg** [comment]
Oops I misread. My bad! :+1: Good fix!

**Comment by mrjbq7** [comment]
It's all good!
