### ISSUE TITLE
Deploy loads .factor-rc?

### ISSUE THREAD

**Issue by mrjbq7** [slavapestov/factor#1415]
I'm not sure when this became a problem, or if it always was, but my deploy doesn't work because of my ``.factor-rc``:

```
$ ./factor
IN: scratchpad "hello-world" deploy
...


$ ./Hello\ world\ \(console\)/hello-world 
Factor 0.98 x86.64 (1691, heads/master-0-ga8b3642, Tue May 12 09:30:20 2015)
[Clang (GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53))] on macosx
:user-init-errors - show 1 rc file errors
IN: scratchpad :user-init-errors

==== /Users/jbenedik/.factor-rc

/Users/jbenedik/.factor-rc

1: USE: editors.macvim
                      ^
Vocabulary does not exist
name "editors.macvim"
```

**Comment by erg** [comment]
Can we fix this by removing the ``.factor-rc`` startup hook for deployed images?

**Comment by mrjbq7** [comment]
Is it weird that ``embedded?`` always returns false?

```
$ grep OBJ_EMBEDDED *
factor.cpp:  special_objects[OBJ_EMBEDDED] = false_object;
objects.hpp:  OBJ_EMBEDDED = 15,  /* are we embedded in another app? */
```

Maybe thats why it's starting the listener?

And for some reason, ``"hello-world" deploy`` doesn't make a binary that prints hello world.  Does it work for you at all?

**Comment by erg** [comment]
``embedded?`` was for using factor.dll on Windows CE.

**Comment by mrjbq7** [comment]
Hmm, okay then thats not the issue, but my ``hello-world`` deployed image doesn't work.

We should have a test that deploys it, runs it, and checks output is hello-world.

**Comment by erg** [comment]
+1

**Comment by mrjbq7** [comment]
So it seems like console-only deploys aren't working?

**Comment by mrjbq7** [comment]
Well, I added a test in 17b369972ff8301a40a74802812184fee5f0ca99 with some dubious ``deploy-path`` thingy, but it still doesn't fix my ``hello-world`` :-)

**Comment by erg** [comment]
I was really wrong about ``embedded`` in this context.

Neat command for finding recent changes in a subdirectory:

```
find . -type f  | xargs -L1 -t git blame | grep 2015-
```
