### ISSUE TITLE
older gcc and clang can't compile factor correctly

### ISSUE THREAD

**Issue by erg** [slavapestov/factor#1440]
It's obvious, because you get a compiler error, but maybe there are versions that compile successfully but are subtly wrong?

We should enforce a minimum version for gcc, clang, and visual studio in factor.sh (rather than switch to ``cmake``) and we should document this in the ``README.md``.

What are safe minimum versions?

```
Not safe:
gcc 4.7.2
Debian clang version 3.0-6.2 (tags/RELEASE_30/final) (based on LLVM 3.0)
```

```
Safe:
visual studio vc2015
visual studio vc2013 works too!
visual studio vc2012 works!

ergmac:factor erg$ [master*] clang --version
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.4.0
Thread model: posix

erg@ubuntu64:~/factor$ gcc --version
gcc (Ubuntu 4.9.2-10ubuntu13) 4.9.2
```

Side note:
I love how apple aliases gcc to clang. Haha.
```
ergmac:factor erg$ [master*] gcc
clang: error: no input files
```

**Comment by bjourne** [comment]
4.8.4-2 safe:
```
$ gcc --version         
gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
```
I wonder what the Windows safe version is. Hopefully it's one of the free VS versions so you don't need to buy a pay-for compiler to compile Factor on Windows.

**Comment by erg** [comment]
MSFT is an open-source/free-as-in-beer/free-as-in-speech altruistic company and champion of developers developers developers. Visual Studio 2013 and 2015 are both free for personal use and both compile Factor.

**Comment by jonenst** [comment]
So I went on a hunt for gcc and clang packages:

gcc:
safe : gcc (GCC) 4.7.4 from https://hub.docker.com/_/gcc/
safe : gcc-4.7 (Ubuntu/Linaro 4.7.3-12ubuntu1) 4.7.3 from http://packages.ubuntu.com/trusty/gcc-4.7
safe: gcc-4.8 (Ubuntu 4.8.1-2ubuntu1~12.04) 4.8.1 from https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test

So we have <=gcc4.7.2 bad and >=gcc4.7.3 good.
I think gcc 4.8.0 is bad  based on the comment from https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54277#c1 and >=gcc4.8.1 is good.
I guess 4.9 is all good

clang:
safe : Ubuntu clang version 3.3-5ubuntu4~precise1 (branches/release_33) (based on LLVM 3.3) from http://packages.ubuntu.com/precise-updates/devel/clang-3.3
safe: Debian clang version 3.1-3eudoxos1 (branches/release_31) (based on LLVM 3.1) from https://launchpad.net/~eudoxos/+archive/ubuntu/llvm-3.1

So I guess < 3.0 is not good and >= 3.1 is good

**Comment by mrjbq7** [comment]
what a pain.  also thanks @jonenst
