### ISSUE TITLE
UI requires you to run Factor from an application bundle

### ISSUE THREAD

**Issue by mrjbq7** [slavapestov/factor#1452]
On Mac OS X, we get this error if trying to "launch" a UI from the command-line:

```
$ ./factor
IN: scratchpad [ "Hello, world" <label> "Testing" open-window ] with-ui
The UI requires you to run Factor from an application bundle.

Type :help for debugging help.
```

But this works:

```
$ ./Factor.app/Contents/MacOS/factor -run=listener
IN: scratchpad [ "Hello, world" <label> "Testing" open-window ] with-ui
```

Which is weird because ``factor`` is just a symlink:

```
$ ls -l factor
factor -> Factor.app/Contents/MacOS/factor
```

So....... seems like we should be able to fix this.

**Comment by mrjbq7** [comment]
Although I just noticed we don't get the command-line back when we close the window, so perhaps thats the reason for the assert.

**Comment by erg** [comment]
You can't do this on Mac. You're only supposed to run bundle apps with ``open`` or from the dock or finder.
