### ISSUE TITLE
Crash when running deploy tool

### ISSUE THREAD

**Issue by bpollack** [slavapestov/factor#1458]
I've recently noticed a new crash when running the deploy tool. No matter what vocabulary I attempt to deploy, I get an immediate traceback that looks like this.

```
$ factor -e='USE: tools.deploy "tools.tree" deploy'
{
    "tree/tools.tree"
    "-pic=0"
    "-i=/Users/benjamin/Library/Caches/org.factorcode.Factor/stagi..."
    "-vocab-manifest-out=/var/folders/d0/d3f0c52j3018yng5pxdc7d100..."
    "-deploy-vocab=tools.tree"
    "-deploy-config=/var/folders/d0/d3f0c52j3018yng5pxdc7d100000gn..."
    "-output-image=/var/folders/d0/d3f0c52j3018yng5pxdc7d100000gn/..."
    "-resource-path=/Users/benjamin/src/factor/"
    "-run=tools.deploy.shaker"
}
fatal_error: Double fault: 0x100284ff8
Process exited with error code T{ signal { n 6 } }

Launch descriptor:

T{ process
    { command
        {
            "tree/tools.tree"
            "-pic=0"
            "-i=/Users/benjamin/Library/Caches/org.factorcode.Factor/stagi..."
            "-vocab-manifest-out=/var/folders/d0/d3f0c52j3018yng5pxdc7d100..."
            "-deploy-vocab=tools.tree"
            "-deploy-config=/var/folders/d0/d3f0c52j3018yng5pxdc7d100000gn..."
            "-output-image=/var/folders/d0/d3f0c52j3018yng5pxdc7d100000gn/..."
            "-resource-path=/Users/benjamin/src/factor/"
            "-run=tools.deploy.shaker"
        }
    }
    { environment H{ } }
    { environment-mode +append-environment+ }
    { stdin +closed+ }
    { stdout T{ fd { disposed t } { fd 17 } } }
    { stderr +stdout+ }
    { priority +low-priority+ }
    { group +same-group+ }
    { status T{ signal { n 6 } } }
    { pipe
        T{ pipe
            { in T{ fd { disposed t } { fd 16 } } }
            { out T{ fd { disposed t } { fd 17 } } }
        }
    }
}
(U) Quotation: [ c-to-factor => ]
    Word: c-to-factor
(U) Quotation: [ [ (get-catchstack) push ] dip call => (get-catchstack) pop* ]
(O) Word: command-line-startup
(O) Method: M\ unix deploy*
(O) Word: make-deploy-image-executable
(O) Word: make-deploy-image
(O) Word: check-success
(O) Word: process-failed
(O) Method: M\ object throw
(U) Quotation: [
        OBJ-CURRENT-THREAD special-object error-thread set-global
        current-continuation => error-continuation set-global
        [ original-error set-global ] [ rethrow ] bi
    ]
```

Note the double fault, which makes me think this may be crashing in the GC or something similar.

As noted, this applies to any vocabulary I've tried. I haven't tried doing a deploy recently, so other than "within the last month or two", I can't immediately bisect this further, but I can try to spend a little bit of time on it tomorrow.

**Comment by mrjbq7** [comment]
Which platform? We aren't seeing any failures on the build farm.

It might be stale staging images, can you try running ``delete-staging-images`` and then re-running deploy?

**Comment by bpollack** [comment]
Sorry, should've mentioned that this is happening on OS X 10.10.5. But I don't think it's stale images; I've rebuilt them myself and grabbed them again from upstream. That said, I'll explicitly blow them out and try again, just in case.

**Comment by bpollack** [comment]
Uh, actually, where is `delete-staging-images`? Doesn't seem to be a make target or a `build.sh` target.

**Comment by mrjbq7** [comment]
``USE: tools.deploy.backend delete-staging-images``

**Comment by mrjbq7** [comment]
We should really version the staging images, it sucks they can get out-of-sync with the boot/factor image.

**Comment by mrjbq7** [comment]
(Our deploy tests used to delete the staging images before running, at some point we moved that into a word that can be called by users, next step is making it so the user doesn't have to call it!)

**Comment by bpollack** [comment]
Sigh. That fixes it. I didn't even know that was a thing.

**Comment by mrjbq7** [comment]
It shouldn't be a thing, hah! Undocumented and error-prone stuff sucks but we will give deploy some loving as soon as parser and new release stabilize. Glad it fixed it for you!

**Comment by bpollack** [comment]
I mean, seriously, I'm just happy that you, erg, and bjourne keep hacking on this. I love hacking in Factor, and I never have the time to do something meaningful, so it's always nice to see things steadily progressing every time I get a chance. :)
