### ISSUE TITLE
Standardize comment characters

### ISSUE THREAD

**Issue by mrjbq7** [slavapestov/factor#1467]
We use both ``!`` and ``#!``.  We should standardize on one or the other.

**Comment by bjourne** [comment]
I thought `#!` was just to make Factor she-bang compatible?

**Comment by mrjbq7** [comment]
It was (is?) used as a standard comment line in a few vocabs, probably by people whose editors know about ``#`` as comment in other languages. Maybe we start by cleaning up the uses-as-comments, and leave the uses-as-shebang, then see where it goes.

**Comment by mrjbq7** [comment]
Removed all of the ``#!`` comments in e477f6996f57abc0d0f984d5b689ac731e408a82.

The shebang is "natively" supported in the lexer so we should be able to get rid of ``#!``.

@erg?

**Comment by mrjbq7** [comment]
Okay, got rid of ``#!`` and changed the lexer in eaa65bc66f8b006fb9deb970fa898f07591f6e22 because it required ``#!`` to be defined syntax, now it just skips over shebang on the first line.
