### ISSUE TITLE
c++ compile error

### ISSUE THREAD

**Issue by erg** [slavapestov/factor#1481]
@bjourne Your recent patches broke something. I might debug it if you're not around to fix.

**Comment by bjourne** [comment]
Ops. I'll look.

**Comment by mrjbq7** [comment]
I think I fixed it. char* to const char*

**Comment by bjourne** [comment]
Awesome! So the crashes on the windows build machine is for something else?

**Comment by mrjbq7** [comment]
I think "crashed builder" is @erg speak for needs to be rebooted or something.  But I'm not a super-human running our build farm like @erg.

**Comment by erg** [comment]
I have a dual boot windows/linux machine and when the email says "2 crashed build machines" it's because that machine is in linux. I would like to move the Windows masons to rackspace soon/eventually.

Thanks for fixing!
