### ISSUE TITLE
Pasting long lines into the listener doesnt work

### ISSUE THREAD

**Issue by bjourne** [slavapestov/factor#1486]
Make a really long string like `"aaaaa....aaa"` with more than 4k a's or so. If you copy paste it into the console listener it breaks. The string gets truncated or something like that. It works when you run it with the readline listener though. The one you get with `-run=readline-listener`.

**Comment by bjourne** [comment]
It's a stupid Unix limitation. http://unix.stackexchange.com/questions/131105/how-to-read-over-4k-input-without-new-lines-on-a-terminal But it breaks FUEL because it regularly sends much longer lines than that to Factor.

**Comment by mrjbq7** [comment]
I didn't see an obvious workaround.  Does FUEL send full buffers, is that why?

**Comment by bjourne** [comment]
Yes it dynamically creates very long lines when you run `fuel-update-usings`.

**Comment by jonenst** [comment]
what about the base 64 with new lines workaround?
Le 5 oct. 2015 10:05 PM, "Björn Lindqvist" <notifications@github.com> a
écrit :

**Comment by bjourne** [comment]
I committed some code which should fix the bug. The FUEL feature I'm talking about is that you can press C-c C-e C-u and it automatically fixes and sorts your vocabs using list. It's very useful and shouls work now.

**Comment by bjourne** [comment]
Funny that it works out of the box on Windows.
