### ISSUE TITLE
memory tests fail on win32

### ISSUE THREAD

**Issue by erg** [slavapestov/factor#1489]
First time this happened was 0f387e750d4f7a8dca06af95faacdd9482d467d4 but it looks like that patch is unrelated.

```
Unit test failures

resource:core/memory/memory-tests.factor
Details:
==== resource:core/memory/memory-tests.factor

resource:core/memory/memory-tests.factor: 14

Must Fail: {
    [
        os windows? "C:\\windows\\hello-windows"
        "/usr/bin/hello-unix" ? save-image
    ]
}

Did not fail

[Traceback]
```

**Comment by erg** [comment]
It's not random, the ``save-image`` word is broken somehow. There is no ``c:\\windows\\hello-windows`` file created and no error.

**Comment by erg** [comment]
@bjourne What's this supposed to test?

85784c52

**Comment by mrjbq7** [comment]
I assume those paths are supposed to fail with no-permissions?

**Comment by mrjbq7** [comment]
Hmm, that test did not fail on my mac64 either.

**Comment by mrjbq7** [comment]
(As an aside, it would be nice if the test report was homoiconic so I could paste it in).

**Comment by bjourne** [comment]
Yes it's a simple test to check that you get a permission error. But if the build bot runs using the administrator account it doesn't work. :) Maybe there is a deeper issue if the file isn't created.

**Comment by mrjbq7** [comment]
Seems fixed.
