### ISSUE TITLE
Permission to use Factor logo in presentation

### ISSUE THREAD

**Issue by kanaka** [slavapestov/factor#1492]
I'm going to be doing a presentation about mal (https://github.com/kanaka/mal) at midwest.io. Factor is one of the implementations and I would like to use a Factor logo in the presentation as part of a list of mal implementations. I found this directory of Factor logos/icons: https://github.com/slavapestov/factor/tree/master/misc/icons. It might be useful if the license.txt file in that directory had some more detail on what permissions are granted in terms of using the logo. Can I get permission to use a Factor logo in my presentation (and the subsequent published video/materials from the conference)?

**Comment by mrjbq7** [comment]
Yes that would be okay. We are updating the icon for the soon to be released 0.98 (maybe one or two weeks away).  If you want the newer icon let us know. 

I'm not sure if the intention would be to have a different license for the icons than the code but we are pretty permissive with BSD license.

**Comment by kanaka** [comment]
@mrjbq7 Thanks! The presentation is Nov 9. If you have something before then and you remember to update this bug before then (because I'm sure I'll forget to check), I would be happy to switch it to the new one.

**Comment by mrjbq7** [comment]
Would you be interested in a pull request for some of the factor code in mal?

**Comment by kanaka** [comment]
@mrjbq7 Certainly! I'm always interested in contributions that improve the implementations, especially if they make it more idiomatic. FYI, the original factor implementation was done by @jordanlewis
