### ISSUE TITLE
Url query parameters aren't kept in order

### ISSUE THREAD

**Issue by bjourne** [slavapestov/factor#1502]
E.g if you type

```factor
IN: scratchpad URL" /?c=d&a=b&e=f" .
URL" /?a=b&c=d&e=f"
```
Note how the order is switched.

**Comment by mrjbq7** [comment]
Maybe should use a `linked-assoc` to store query params instead of hashtable...?

**Comment by mrjbq7** [comment]
Fixed in f7b7b5afbf419cc8ea06e1c55e21b9bb5a32cecd using a ``linked-hash`` (and 40d454758e364b25cd623bdb65b411163da3de80 makes ``linked-hash`` have nice ``LH{ }`` pprint for when you click on a URL to inspect it).

**Comment by bjourne** [comment]
Cool! But won't that break the unit tests?

**Comment by mrjbq7** [comment]
Haha, it did. Silly me didn't run them before committing.

Fixed in a73340a032c60e457d6e0b9a50a4285772328c81.

**Comment by mrjbq7** [comment]
@bjourne I haven't looked, but should these be considered "equal"?

```
URL" http://foo.com?a=1&b=2
URL" http://foo.com?b=2&a=1
```

**Comment by mrjbq7** [comment]
Ruby and Python don't think those should be equal, but thats mainly because they store the query as a string... perhaps we should also?  There really isn't a good reason why it has to be parsed into a hashtable in the URL object.

**Comment by bjourne** [comment]
I don't think they are equal (they don't *look* equal), but I haven't looked at the rfcs.

**Comment by mrjbq7** [comment]
I'm going to just close this bug since I think it's not an issue.
