### ISSUE TITLE
Can't open help in OSX

### ISSUE THREAD

**Issue by knutesten** [slavapestov/factor#1505]
Pressing F1 to open help in osx does not work. I get the following error: 
```
An error occurred while drawing the world T{ world f ~array~ ~array~ f f ~vector~ ~array~ ~debugger~ t t f....
This world has been deactivated to prevent cascading errors.
gl-error-tuple
function f
code     1286
string   "Invalid framebuffer operation"
```

**Comment by mrjbq7** [comment]
That is an error in the 0.97 release, but it was fixed in the current git master which will become 0.98 when we are ready to do the next release.

See #1379
