### ISSUE TITLE
Linux window manager bug

### ISSUE THREAD

**Issue by mrjbq7** [slavapestov/factor#1506]
Bug reported on the mailing list, maybe due to some of the recent GTK backend changes:

> I use the window manager awesome (http://awesome.naquadah.org/).
> 
> With
> Factor 0.98 x86.64 (1720, heads/master-7b18618b3e, Wed Nov  4 12:55:22
> 2015) [GCC 4.8.4] on linux
> there is a problem:
> 
> When I return to my Factor tag (workspace) the Factor windows listener
> and browser do not refresh but remain transparent. When I change focus
> inside the tag, the two Factor windows appear again as soon as they are
> left and then work normally until next tag change.
> 
> Until
> Factor 0.98 x86.64 (1715, heads/master-d5c5a1389d, Sun Sep 20 16:49:23
> 2015) [GCC 4.8.4] on linux
> all worked fine.

Here are the changes implied:

https://github.com/slavapestov/factor/compare/d5c5a1389d...7b18618b3e

**Comment by bjourne** [comment]
That's the main suspect. :) I'll check out awesomewm today and see if I can see what happens. All DE:s on linux work differently, very annoying.

**Comment by bjourne** [comment]
Hm. I'm not able to reproduce. It could be some gfx driver issue... But I almost never use tiling wm:s so it might be that I'm not triggering it the right way.

**Comment by GeorgSimon** [comment]
I'm still searching for the name of my gfx card.
My computer says

$ uname -a
Linux tuxedo 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ lspci -nnk | grep "VGA\|'Kern'\|3D\|Display" -A2
00:02.0 VGA compatible controller [0300]: Intel Corporation Crystal Well Integrated Graphics Controller [8086:0d26] (rev 08)
	Subsystem: CLEVO/KAPOK Computer Device [1558:7410]
	Kernel driver in use: i915

**Comment by GeorgSimon** [comment]
I just tried another window manager: xfce4. The Factor listener window appears, shows the title "Listener", but remains transparent showing no content.

**Comment by GeorgSimon** [comment]
my hardware:
Intel Iris Pro Graphics 5200
Intel Core i7-4750HQ

**Comment by mrjbq7** [comment]
I have a similar bug on an arch linux box that I just installed Factor onto.  The window is black with no contents until I drag it around and then it is painted.

**Comment by mrjbq7** [comment]
Also, scrolling in the Factor window is a lot slower than scrolling in my other non-Factor windows.

**Comment by bjourne** [comment]
But scrolling has always been laggish in Factor, hasn't it? Maybe you or @GeorgSimon can change line 121 in `ui/gadgets/worlds/worlds.factor` which reads `0 >>active?` to `50 >>active?` or `100 >>active?`? If that helps, then it is very easy to narrow down the source of the bug.

**Comment by erg** [comment]
#1487

**Comment by GeorgSimon** [comment]
I wanted to try ```100 >>active``` and followed
http://concatenative.org/wiki/view/Factor/Building%20Factor

But my gcc is refused although it's version is 4.8.4

git/factor$ ./build-support/factor.sh update
Finding OS...
Finding ARCH...
Checking for all(clang clang++)...all not found.
Checking for all(gcc g++)...found!
gcc version required >= 4.7.3, != 4.8.0, >= 4.8.1, got 4.8
error: high enough version of either (clang/clang++) or (gcc/g++) required!
git/factor$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by bjourne** [comment]
You don't have to recompile your whole Factor. Just make the change, start factor in console mode then type: `"/path/to/the/factor-repo/ui/gadgets/worlds/worlds.factor" run-file save`

**Comment by GeorgSimon** [comment]
No effect.  No faster scrolling and windows still remain transparent as described above.

I could not find out how to start factor in console mode and used the listener. After restarting the listener I could verify the change:
IN: scratchpad Command: continue-restart
1: Note:
Added "ui.gadgets.worlds" vocabulary to search path
USING: accessors concurrency.promises kernel ui.gadgets
ui.gadgets.tracks ;
IN: ui.gadgets.worlds
: new-world ( class -- world )
    vertical swap new-track t >>root? ```100 >>active?```
    { 0 0 } >>window-loc f >>grab-input?
    V{ } clone >>window-resources <promise> >>promise ;

**Comment by bjourne** [comment]
I see it now. KDE (which is my favorite de) sends a configure event after the map event. But awesomewm and xfce sends all their configure events before the map event.

**Comment by GeorgSimon** [comment]
Yes, it works.
