### ISSUE TITLE
"Keyboard gestures" article has incorrect documentation for SPACE key-down gesture

### ISSUE THREAD

**Issue by rationalrevolt** [slavapestov/factor#1509]
The documentation notes: `The RET, TAB and SPACE keys are never delivered in their literal form ("\n", "\t" or " ")`, but the `handle-gesture` word seems to deliver the SPACE `key-down` gesture with the `sym` slot set to `" "` instead of  `"SPACE"`.

**Comment by bjourne** [comment]
Good catch! I've updated it.
