### ISSUE TITLE
ui.gadgets: Allocating resources in graft* doesn't work as documented

### ISSUE THREAD

**Issue by rationalrevolt** [slavapestov/factor#1510]
I faced a problem drawing textures in a new window. when I create the gadget and add it to the listener using `gadget.` the image shows corretly, when I create the gadget and use `open-window`, the
image does not show up on the new window.

````factor
TUPLE: i-gadget < gadget
    image texture ;

: <i-gadget> ( path -- gadget )
    [ i-gadget new ] dip load-image >>image ;

M: i-gadget pref-dim*
    image>> dim>> [ 20 + ] map ;

M: i-gadget graft*
    dup find-gl-context
    dup image>> { 0 0 } <texture> >>texture drop ;

M: i-gadget ungraft*
    dup find-gl-context
    dup texture>> dispose
    f >>texture drop ;

M: i-gadget draw-gadget*
    [ { 10 10 } ] dip texture>> [ draw-texture ]
    curry with-translation ;

! In the listener

"vocab:images/sprites/game_drop.png" <i-gadget> gadget.

! the above works and shows the image in the listener

"vocab:images/sprites/game_drop.png" <i-gadget> "i-gadget" open-window

! the above opens a new window but the image does not show
````

I see that moving the texture creation code from `graft*` to `draw-gadget*` solves the issue. I'm wondering if this is a bug, since the documentation for `graft*` mentions that resources can be allocated on this method (and to use `find-gl-context` to ensure the correct GL context is setup before allocating the resources).

The modified the code shown below works correctly:
````factor
M: i-gadget graft*
     drop ;

M: i-gadget draw-gadget*
     [ { 10 10 } ] dip
     dup texture>> [ ]
     [ dup image>> { 0 0 } <texture> >>texture texture>> ] ?if
     [ draw-texture ] curry with-translation ;
````

`<image-gadget>` seems to have been implemented in the same way though (i.e. 
setting up textures is done on the 1st call into `draw-gadget*`).

**Comment by bjourne** [comment]
Yeah it looks like the docs are wrong. `find-gl-context` says that you can allocate gl resources in `graft*` but you can't because gl hasn't been initialized there. I believe your original code didn't work because `<texture>` calls `glBindTexture` and it happened before gl initialization. In fact, `find-gl-context` probably should throw an error or something if it is called before gl is ready to be used.

**Comment by bjourne** [comment]
No my explanation was wrong. It turns out that if you just do some of the gl setup a little earlier, you can allocate textures in the `graft*` method no problem.
