### ISSUE TITLE
cannot find change-slot words after a tuple is defined

### ISSUE THREAD

**Issue by Javran** [slavapestov/factor#1519]
I'm new to the language, and it's more likely that I've missed something than a bug:

The following code works only in Listener: 

```factor
IN: test
USING: kernel prettyprint math ;

TUPLE: foo bar baz ;

T{ foo f 10 20 } 
[ 200 + ] change-bar .
```

when I save it to a file (with proper vocabulary name), it no longer works,
the error message reads:

```
9: [ 200 + ] change-bar .
                       ^
No word named “change-bar” found in current vocabulary search path
(U) Quotation: [ c-to-factor => ]
    Word: c-to-factor
(U) Quotation: [ [ (get-catchstack) push ] dip call => (get-catchstack) pop* ]
(O) Word: command-line-startup
(O) Word: run-script
(O) Word: run-file
(O) Word: parse-file
(O) Word: parse-stream
(O) Word: finish-compilation-unit
(O) Method: M\ optimizing-compiler recompile
(O) Word: compile-word
(O) Word: frontend
(O) Word: build-tree-with
(O) Method: M\ word (build-tree)
(O) Word: infer-quot-here
(O) Word: infer-ndip
(O) Word: infer-quot-here
(O) Method: M\ input-parameter infer-call*
(O) Word: unknown-macro-input
(O) Method: M\ object throw
(U) Quotation: [
        OBJ-CURRENT-THREAD special-object error-thread set-global
        current-continuation => error-continuation set-global
        [ original-error set-global ] [ rethrow ] bi
    ]
```
I'm using Factor compiled from latest github repo. also I believe I've configured `.factor-roots` correctly.

**Comment by mrjbq7** [comment]
The slot words are currently defined in the accessors vocabulary, and created when a slot of that name is first defined.

If you:

    USE: accessors

It should fix your error. 

You should also see this as a "restart" which is a correctable error when loading your code in the listener.

**Comment by Javran** [comment]
Thanks for your response, `USE: accessors` does the trick.
I guess it's worth mentioning somewhere in the document, I thought I had missed to load some vocabularies when I saw the error, but wasn't know it was `accessors`.
