### ISSUE TITLE
./factor -run=mason.build should just work™

### ISSUE THREAD

**Issue by erg** [slavapestov/factor#187]
I want to run this command and have it make the ~builds directory, clone factorcode's git, build factor, bootstrap factor, and exit.

**Comment by erg** [comment]
This has been fixed. Closing!

**Comment by mrjbq7** [comment]
Did it just start working? I thought it required some fixes?

**Comment by erg** [comment]
It creates ~/builds, clones factor git, etc.

Yes, you have to check out some files but those have the mason gmail password etc which I can't really share/automate anyway.
