### ISSUE TITLE
Unicode render problems on Win 7

### ISSUE THREAD

**Issue by mrjbq7** [slavapestov/factor#860]
From the 0.96 release announcement blog comments:

> if you paste "中文" (Chinese characters) to the listener, you will see the question marks in Windows 7. You need to change your Win7 locale to Chinese to see Chinese characters in the listener.

**Comment by erg** [comment]
http://src.chromium.org/chrome/trunk/src/ui/gfx/render_text_win.cc
http://stackoverflow.com/questions/16828868/how-to-automatically-choose-most-suitable-font-for-different-language

**Comment by mrjbq7** [comment]
Unicode be crazy, see also #1382.  Not sure if that is a mac-specific or bug on other platforms.
