### ISSUE TITLE
Clean up C++ code in VM and settle on coding conventions

### ISSUE THREAD

**Issue by slavapestov** [slavapestov/factor#97]
There are some stylistic problems in the code:

- inconsistent naming convention for constants and enum members (some are upper case, some are not)
- 'explicit' is used for non-one arg constructors (its unnecessary)
- some constructor parameters have a _ suffix. This is unusual and unnecessary: explicit foo(int x) : x(x) { } works fine, no need to name the parameter x_
- too many #defines
- various other inconsistent naming conventions

I suggest cleaning up the code and picking a style guide. Google's C++ style guide might be a good place to start.

**Comment by erg** [comment]
@bjourne How far have we come on this with your C++11 changes? Want to work toward closing this when you're refactoring the vm?

**Comment by bjourne** [comment]
Sure, but I think the code is pretty good as it is. Maybe most of it has already been fixed? The functor objects were an eyesore but with c++11 we can have lambda functions in most places instead.
